DELETE http://localhost:8080/events/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im11c3RhcGhhLmxhbWhhZmFkQGFpYWMubWEiLCJleHAiOjE3MDk2MzkzNTUsInVzZXJJZCI6MX0.47MbKyDVLoqJSNsbDC5FlFlgBIqnDR3XOdco3AqVl-o